#!/usr/bin/env python3
"""Write a SwiftPM package that builds a Flutter app's iOS Runner and its plugins.

  gen-shell-package.py <flutter app dir> <output package dir> <min iOS>

Reads the plugin list Flutter writes to .flutter-plugins-dependencies and each
plugin's own Package.swift. The app's Swift sources and plugin registrant are
copied in; the bridging header becomes an `import PluginRegistrant`.
"""
import json
import os
import re
import shutil
import sys

app, out, min_ios = os.path.abspath(sys.argv[1]), os.path.abspath(sys.argv[2]), sys.argv[3]
runner = os.path.join(app, "ios", "Runner")
deps = json.load(open(os.path.join(app, ".flutter-plugins-dependencies")))

plugins = []
for p in deps["plugins"]["ios"]:
    if not p.get("native_build", True) or p.get("dev_dependency"):
        continue
    name, root = p["name"], p["path"]
    pkg = next(
        (os.path.join(root, d, name) for d in ("ios", "darwin")
         if os.path.isfile(os.path.join(root, d, name, "Package.swift"))),
        None,
    )
    if pkg is None:
        sys.exit(f"{name}: no ios/ or darwin/ Package.swift; this plugin needs CocoaPods")
    manifest = open(os.path.join(pkg, "Package.swift")).read()
    library = re.search(r'\.library\(\s*name:\s*"([^"]+)"', manifest)
    if library is None:
        sys.exit(f"{name}: {pkg}/Package.swift declares no .library product to link")
    product = library.group(1)
    plugins.append((name, pkg, product))

src_runner = os.path.join(out, "Sources", "Runner")
src_reg = os.path.join(out, "Sources", "PluginRegistrant")
os.makedirs(src_runner, exist_ok=True)
os.makedirs(os.path.join(src_reg, "include"), exist_ok=True)

for f in os.listdir(runner):
    if f.endswith(".swift"):
        body = open(os.path.join(runner, f)).read()
        if "GeneratedPluginRegistrant" in body:
            body = "import PluginRegistrant\n" + body
        open(os.path.join(src_runner, f), "w").write(body)
shutil.copy(os.path.join(runner, "GeneratedPluginRegistrant.h"), os.path.join(src_reg, "include"))

# Keep only the plugins this build links: dev dependencies are registered in
# the generated file but are not part of a release app.
kept = {name for name, _, _ in plugins}
registrant = open(os.path.join(runner, "GeneratedPluginRegistrant.m")).read()
def drop_block(m):
    return m.group(0) if m.group(1) in kept else ""
registrant = re.sub(r"#if __has_include\(<([^/]+)/[^>]+>\)\n.*?#endif\n", drop_block, registrant, flags=re.S)
imported = set(re.findall(r"#import <[^/]+/([A-Za-z0-9_]+)\.h>", registrant))
registrant = "\n".join(
    line for line in registrant.split("\n")
    if not (m := re.match(r"\s*\[([A-Za-z0-9_]+) registerWithRegistrar", line)) or m.group(1) in imported
)
open(os.path.join(src_reg, "GeneratedPluginRegistrant.m"), "w").write(registrant)

# Plugins are copied under Packages/ beside a FlutterFramework package, the
# layout Flutter generates on a Mac: a newer plugin manifest depends on
# `.package(name: "FlutterFramework", path: "../FlutterFramework")`, which only
# resolves from there. The package is a placeholder; the Flutter module itself
# still comes from the framework search path the build passes.
packages = os.path.join(out, "Packages")
if os.path.isdir(packages):
    shutil.rmtree(packages)
framework_pkg = os.path.join(packages, "FlutterFramework")
os.makedirs(os.path.join(framework_pkg, "Sources", "FlutterFramework"))
open(os.path.join(framework_pkg, "Package.swift"), "w").write("""// swift-tools-version: 5.9
// Generated by gen-shell-package.py. Do not edit.
import PackageDescription

let package = Package(
  name: "FlutterFramework",
  products: [.library(name: "FlutterFramework", targets: ["FlutterFramework"])],
  targets: [.target(name: "FlutterFramework")]
)
""")
open(os.path.join(framework_pkg, "Sources", "FlutterFramework", "FlutterFramework.swift"), "w").write(
    "// Placeholder: plugins that declare a FlutterFramework dependency link this.\n")
local = []
for name, pkg, product in plugins:
    dest = os.path.join(packages, os.path.basename(pkg))
    # Links are followed, not kept: a package may link its sources from the
    # plugin's parent directory (Sources/x -> ../../Classes), and a relative
    # link would point nowhere once the package has moved.
    try:
        shutil.copytree(pkg, dest, symlinks=False, ignore=shutil.ignore_patterns(".build", ".swiftpm"))
    except (shutil.Error, OSError) as error:
        sys.exit(f"{name}: cannot copy {pkg} into the shell package: {error}")
    local.append((name, dest, product))
plugins = local

dep_lines = "\n".join(f'    .package(path: "Packages/{os.path.basename(pkg)}"),' for _, pkg, _ in plugins)
prod_lines = "\n".join(
    f'        .product(name: "{product}", package: "{os.path.basename(pkg)}"),' for _, pkg, product in plugins
)
open(os.path.join(out, "Package.swift"), "w").write(f"""// swift-tools-version: 5.9
// Generated by gen-shell-package.py. Do not edit.
import PackageDescription

let package = Package(
  name: "RunnerShell",
  platforms: [.iOS("{min_ios}")],
  dependencies: [
{dep_lines}
  ],
  targets: [
    .target(
      name: "PluginRegistrant",
      dependencies: [
{prod_lines}
      ]
    ),
    .executableTarget(
      name: "Runner",
      dependencies: ["PluginRegistrant"],
      swiftSettings: [.unsafeFlags(["-parse-as-library"])]
    ),
  ]
)
""")
print(f"shell package: {len(plugins)} plugins: {', '.join(n for n, _, _ in plugins)}")
